coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: 'header, diff, flags, components, footer'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - 'test/**/*'
  - 'tests/**/*'
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '**/*.config.*'
  - '**/node_modules/**'
