name: 'Restore Next.js build artifact'
description: 'Downloads and extracts Next.js build artifact'

inputs:
  artifact-name:
    description: 'Name of the build artifact'
    required: false
    default: 'nextjs-build'

runs:
  using: 'composite'
  steps:
    - name: Restore build from cache
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: .next
        key: nextjs-build-${{ github.sha }}
        fail-on-cache-miss: true

    - name: Verify build artifact
      shell: bash
      run: |
        if [ ! -d ".next" ]; then
          echo "Error: .next directory not found after artifact download"
          exit 1
        fi
        echo "✓ Build artifact restored successfully"
        ls -lh .next
