name: 'Restore Next.js build artifact'
description: 'Downloads and extracts Next.js build artifact'

inputs:
  artifact-name:
    description: 'Name of the build artifact'
    required: false
    default: 'nextjs-build'

runs:
  using: 'composite'
  steps:
    - name: Download build artifact
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
      with:
        name: ${{ inputs.artifact-name }}
        path: .

    - name: Verify build artifact
      shell: bash
      run: |
        if [ ! -d ".next" ]; then
          echo "Error: .next directory not found after artifact download"
          exit 1
        fi
        echo "✓ Build artifact restored successfully"
        ls -lh .next
